paths:
  test_dir: c:\Users\mohtashaa\Downloads\retina_segmentation_3\retina_segmentation\test\image.zip
  mask_dir: c:\Users\mohtashaa\Downloads\retina_segmentation_3\retina_segmentation\test\annotations.zip
  model_path: c:\Users\mohtashaa\Downloads\retina_segmentation_3\retina_segmentation\retina_model.pt 
  preprocess_postprocess_path: c:\Users\mohtashaa\Downloads\retina_segmentation_3\retina_segmentation\image_preprocess.py
  output_csv: c:\Users\mohtashaa\Downloads\retina_segmentation_3\retina_segmentation\metrics_results.csv

device:
  name: cpu
